<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-RDSQ4RAL" failures="0" tests="4" name="com.leaftaps.testcases.TC001_VerifyLogin" time="99.373" errors="1" timestamp="2025-05-01T13:52:34 IST" skipped="3">
  <testcase classname="com.leaftaps.testcases.TC001_VerifyLogin" name="runLogin1" time="0.000">
    <skipped/>
  </testcase> <!-- runLogin1 -->
  <system-out/>
  <testcase classname="com.leaftaps.testcases.TC001_VerifyLogin" name="preCondition" time="99.372">
    <error message="Test failed: See report for details." type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Test failed: See report for details.
at com.framework.utils.Reporter.reportStep(Reporter.java:110)
at com.framework.utils.Reporter.reportStep(Reporter.java:128)
at com.framework.selenium.api.base.SeleniumBase.startApp(SeleniumBase.java:646)
at com.framework.testng.api.base.ProjectSpecificMethods.preCondition(ProjectSpecificMethods.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </error>
  </testcase> <!-- preCondition -->
  <system-out/>
  <testcase classname="com.leaftaps.testcases.TC001_VerifyLogin" name="runLogin" time="0.001">
    <skipped/>
  </testcase> <!-- runLogin -->
  <system-out/>
  <testcase classname="com.leaftaps.testcases.TC001_VerifyLogin" name="runLogin2" time="0.000">
    <skipped/>
  </testcase> <!-- runLogin2 -->
  <system-out/>
</testsuite> <!-- com.leaftaps.testcases.TC001_VerifyLogin -->
